// auth.js
export const LOGOUT = "LOGOUT";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const SAVE_USER = "SAVE_USER";
export const FETCH_USER = "FETCH_USER";
export const SAVE_USER_ACTIVE = "SAVE_USER_ACTIVE";
export const SAVE_USER_TYPE = "SAVE_USER_TYPE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_MERCH_SUCCESS = "FETCH_MERCH_SUCCESS";
export const FETCH_MERCH_FAILURE = "FETCH_MERCH_FAILURE";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_LOADING_STATUS = "UPDATE_LOADING_STATUS";

// user.js
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";


export const SAVE_USER_REQUEST = "SAVE_USER_REQUEST";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";

// subscription-setting.js
export const SAVE_SUBSCRIPTION_DATA = "SAVE_SUBSCRIPTION_DATA";
export const SET_PAYMENT_METHODS = "SET_PAYMENT_METHODS";
export const UPDATE_DEFAULT_PAYMENT_METHOD = "UPDATE_DEFAULT_PAYMENT_METHOD";
export const DELETE_PAYMENT_METHOD = "DELETE_PAYMENT_METHOD";

// trademark-alert.js
export const SAVE_TRADEMARK_ALERT_INITIAL_DATA =
    "SAVE_TRADEMARK_ALERT_INITIAL_DATA";

// note.js
export const SAVE_NOTE_INITIAL_DATA = "SAVE_NOTE_INITIAL_DATA";
export const SAVE_NOTES_DATA = "SAVE_NOTES_DATA";

// competition-checker.js
export const SAVE_COMPETITION_CHECKER = "SAVE_COMPETITION_CHECKER";

// merch-tracker.js
export const SAVE_MERCH_TRACKER = "SAVE_MERCH_TRACKER";
export const UPDATE_MERCH_TRACKER = "UPDATE_MERCH_TRACKER";

// keyword-finder.js
export const SAVE_KEYWORD_FINDER = "SAVE_KEYWORD_FINDER";
export const SAVE_SUGGESTION_DETAIL = "SAVE_SUGGESTION_DETAIL";

// theme.js

export const setLayout = "setLayout";

// lang.js
export const SET_LOCALE = "SET_LOCALE";
